### ISSUE TITLE
Ranch Block doesn't display pokemon on/under water? 1.8.9 (v 4.3.0 beta 9)

### ISSUE THREAD

**Issue by Trisscar05** [Pixelmon/Pixelmon-Json#3]
Lemme know if this is the right area for this, I'm not certain due to the lack of people asking what such and such crash log means. XD

So I'm attempting to make an underwater breeding area, here's how it currently looks;
http://imgur.com/a/SMZGp

The pokemon aren't appearing for whatever reason, even with full upgrades and plenty of space both water and land. I even tried submerging the ranch block initially to no avail.
My land-based ranch block works just fine however, even after restarts of the game and reloading the chunks for the water area. The Qwilfish I threw into it to test if swimming pokemon would even render seemed fine, if a tad annoyed that it was on dry land. The logs provided by the MC launcher didn't throw anything that seemed related.

So my question would seem to be, after consulting the wiki, what if anything am I doing wrong? Or is this just a weird interaction with lily pads or ExUtil2's blocks (the glass and most of the stone)?

This is done in a forge profile of vanilla with these mods installed:
Bagginses 2.1.5b
Bibliocraft 2.0.1
Buildcraft 7.2.7
Chameleon 1.1.5
Chisel 0.0.2.6
Dense Ores 2.0.3
Evs-Ivs 4.1.0
extrautils2 0.0.2
Inventory Tweaks 1.60-40
Iron chest 6.0.125.770
JEI 2.28.18.186
Journeymap 5.2.4
Mantle 0.9.2
Optifine HD U H2
Pam's Harvestcraft 1.8.9d
Pixelmon 4.3.0 beta 9
ProjectE PE1.1.4
Random Things 3.6.6
Reliquary 1.3.1.296
Roguelike Dungeons 1.5.0
Storage Drawers 2.7.0
Tinker's Construct 2.2.1
Waila 1.6.0-B3
Waila Harvestability 1.1.7

**Comment by isiliden** [comment]
Go to the forums.
