### ISSUE TITLE
About "sort these into one pull request"

### ISSUE THREAD

**Issue by eva08maicy02** [Pixelmon/Pixelmon-Json#75]
I do not understand, these are scattered, one NPC with one text, how to I pull reques combined into one? :O

**Comment by isiliden** [comment]
You can open pull requests to this repository from your computer, allowing you to merge entire directories if you want to. 

https://desktop.github.com/

 Install this, and login with your Girhub credentials. 

Clone the repo, shown in the screenshot

https://gyazo.com/dcea9fed628d60e07450b03dd94df170

Now you'll have a folder on your PC with this entire repo in there. Copy your files in, then click 'Pull request' on the top right of Github Windows

**Comment by eva08maicy02** [comment]
Okay I'll try to download the installer.
